name: verify-signals
secrets-path: "../secrets.yaml"

staging-settings:
  user-workflow:
    workflow-name: "black-cat-verify-signals-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
